#!/bin/bash
echo 'Enter your name'
read name

if [ $1 == 'grade' ]
then
	case $2 in
	task1)
echo -e "\e[1;34m===========================================================\e[0m"
echo -e "\e[1;34m Grading RHCSA-Section1 Task1 \e[0m"
echo -e "\e[1;34m===========================================================\e[0m"

exists=$(grep -c %end /net.txt 2> /dev/null)
if [[ $exists -gt 0 ]]
then
echo -e "\e[1;32m-----Task Sucessful-----\e[0m"
else 
echo -e "\e[1;31m-----Task not Sucessful-----\e[0m"
fi
	;;


	task2)
echo -e "\e[1;34m===========================================================\e[0m"
echo -e "\e[1;34m Grading RHCSA-Section1 Task2 \e[0m"
echo -e "\e[1;34m===========================================================\e[0m"

exists=$(grep -c boot /boot.doc 2> /dev/null)
if [[ $exists -gt 0 ]]
then
echo -e "\e[1;32m-----Task Sucessful-----\e[0m"
else
echo -e "\e[1;31m-----Task not Sucessful-----\e[0m"
fi
	;;


	task3)
echo -e "\e[1;34m===========================================================\e[0m"
echo -e "\e[1;34m Grading RHCSA-Section1 Task3 \e[0m"
echo -e "\e[1;34m===========================================================\e[0m"

exists=$(grep -c -e network -c -e root /alpha.xls 2> /dev/null)
if [[ $exists -gt 0 ]]
then
echo -e "\e[1;32m-----Task Sucessful-----\e[0m"
else
echo -e "\e[1;31m-----Task not Sucessful-----\e[0m"
fi
	;;


	task4)
	
echo -e "\e[1;34m===========================================================\e[0m"
echo -e "\e[1;34m Grading RHCSA-Section1 Task4 \e[0m"
echo -e "\e[1;34m===========================================================\e[0m"

exists=$(grep -c sbin /loop.txt 2> /dev/null)
echo $exists
if [[ $exists -gt 0 ]]
then
echo -e "\e[1;32m-----Task Sucessful-----\e[0m"
else
echo -e "\e[1;31m-----Task not Sucessful-----\e[0m"
fi
	;;


	task5)

echo -e "\e[1;34m===========================================================\e[0m"
echo -e "\e[1;34m Grading RHCSA-Section1 Task5 \e[0m"
echo -e "\e[1;34m===========================================================\e[0m"

check=0
exists=$(grep -c -e autopart /auto.txt 2> /dev/null)
if [[ $exists -gt 0 ]]
then
	check=$((check+1))
fi


while IFS= read -r line1; do
if [[ $line1 == 'autopart' ]]
then
	while IFS= read -r line2; do
		if [[ $line2 == '# Partition clearing information' ]]
		then
			while IFS= read -r line3; do
				if [[ $line3 == 'clearpart --none --initlabel' ]]
				then 
					check=$((check+1))
				fi
			done < /auto.txt
		fi
	done < /auto.txt
fi
done < /auto.txt

if [ $check -eq 2 ]
then 
	echo -e "\e[1;32m-----Task Sucessful-----\e[0m"
else
	echo -e "\e[1;31m-----Task not Sucessful-----\e[0m"
fi
	;;

	
	task6)
echo -e "\e[1;34m===========================================================\e[0m"
echo -e "\e[1;34m Grading RHCSA-Section1 Task6 \e[0m"
echo -e "\e[1;34m===========================================================\e[0m"
ls /opt/undata/ > a.txt 2> /dev/null

var1=$(cat a.txt | grep myundata 2> /dev/null)

if [ $? == 0 ]
then
        echo -e "\e[1;32m-----Task Sucessful-----\e[0m"
else
        echo -e "\e[1;31m-----Task not Sucessful-----\e[0m"
fi
	;;


	task7)
echo -e "\e[1;34m===========================================================\e[0m"
echo -e "\e[1;34m Grading RHCSA-Section1 Task7 \e[0m"
echo -e "\e[1;34m===========================================================\e[0m"

ls /mnt/mytest/ > b.txt 2> /dev/null

var2=$(cat b.txt | grep fdata 2> /dev/null)

if [ $? == 0 ]
then
        echo -e  "\e[1;32m-----Task Sucessful-----\e[0m"
else
        echo -e "\e[1;31m-----Task not Sucessful-----\e[0m"
fi
	;;

	task8)
echo -e "\e[1;34m===========================================================\e[0m"
echo -e "\e[1;34m Grading RHCSA-Section1 Task8 \e[0m"
echo -e "\e[1;34m===========================================================\e[0m"

ls /tmp/kdata/pdata/ > c.txt 2> /dev/null

var3=$(cat c.txt | grep mdata 2> /dev/null)

if [ $? == 0 ]
then
        echo -e  "\e[1;32m-----Task Sucessful-----\e[0m"
else
        echo -e "\e[1;31m-----Task not Sucessful-----\e[0m"
fi
	;;

	task9)
echo -e "\e[1;34m===========================================================\e[0m"
echo -e "\e[1;34m Grading RHCSA-Section1 Task9 \e[0m"
echo -e "\e[1;34m===========================================================\e[0m"

ls /tmp/kdata/pdata/mdata > d.txt 2> /dev/null

var4=$(cat d.txt | grep 'my fold' 2> /dev/null)

if [ $? == 0 ]
then
        echo -e  "\e[1;32m-----Task Sucessful-----\e[0m"
else
        echo -e "\e[1;31m-----Task not Sucessful-----\e[0m"
fi
	;;

	task10)
echo -e "\e[1;34m===========================================================\e[0m"
echo -e "\e[1;34m Grading RHCSA-Section1 Task10 \e[0m"
echo -e "\e[1;34m===========================================================\e[0m"

ls /mnt/mytest/fdata/ > f.txt 2> /dev/null

var5=$(cat f.txt | grep 'red hat' 2> /dev/null)

if [ $? == 0 ]
then
        echo -e  "\e[1;32m-----Task Sucessful-----\e[0m"
else
        echo -e "\e[1;31m-----Task not Sucessful-----\e[0m"
fi
	;;

	task11)
echo -e "\e[1;34m===========================================================\e[0m"
echo -e "\e[1;34m Grading RHCSA-Section1 Task11 \e[0m"
echo -e "\e[1;34m===========================================================\e[0m"

check=0
while IFS=":" read -r v1 v2 v3 v4 v5 v6 v7
do
        if [[ $v1 == 'redhat' ]]
        then
                check=$((check+1))
        fi
done < /etc/passwd
if [ $check -eq 1 ]
then
      check=$((check+1))
fi
while IFS=":" read -r v1 v2 v3 v4 v5 v6 v7
do
        if [[ $v1 == 'redhat1' ]]
        then
                check=$((check+1))
        fi
done </etc/passwd
if [ $check -eq 2 ]
then
       check=$((check+1))
fi

while IFS=":" read -r v1 v2 v3 v4 v5 v6 v7
do
        if [[ $v1 == 'linux' ]]
        then
                check=$((check+1))
        fi
done < /etc/group
if [ $check -eq 3 ]
then
       check=$((check+1))
fi

ls / > vip.txt
var1=$(cat vip.txt | grep impdata)
if [ $? == 0 ]
then
      check=$((check+1))
fi

ls -ll | grep impdata > vip2.txt
var2=$(cat vip2.txt | grep drwxrwx)
if [ $? == 0 ]
then
     check=$((check+1))

fi
if [ $check -eq 5 ]
then
        echo -e "\e[1;32m-----Task Successful-----\e[0m"
else
        echo -e "\e[1;31m-----Task not Successful-----\e[0m"
fi
	;;

	task12)
echo -e "\e[1;34m===========================================================\e[0m"
echo -e "\e[1;34m Grading RHCSA-Section1 Task12 \e[0m"
echo -e "\e[1;34m===========================================================\e[0m"

check=0
while IFS=":" read -r v1 v2 v3 v4 v5 v6 v7
do
        if [[ $v1 == 'unnati1' ]]
        then
                check=$((check+1))
        fi
done < /etc/passwd
if [ $check -eq 1 ]
then
      check=$((check+1))
fi

while IFS=":" read -r v1 v2 v3 v4 v5 v6 v7
do
        if [[ $v1 == 'unnati2' ]]
        then
                check=$((check+1))
        fi
done < /etc/passwd
if [ $check -eq 1 ]
then
      check=$((check+1))
fi

while IFS=":" read -r v1 v2 v3 v4 v5 v6 v7
do
        if [[ $v1 == 'unnati3' ]]
        then
                check=$((check+1))
        fi
done </etc/passwd
if [ $check -eq 2 ]
then
       check=$((check+1))
fi

while IFS=":" read -r v1 v2 v3 v4 v5 v6 v7
do
        if [[ $v1 == 'admin' ]]
        then
                check=$((check+1))
        fi
done < /etc/group
if [ $check -eq 3 ]
then
       check=$((check+1))
fi

ls / > v1.txt
var1=$(cat v1.txt | grep pdata)
if [ $? == 0 ]
then
      check=$((check+1))
fi

ls -ll | grep pdata > v2.txt
var2=$(cat v2.txt | grep drwxrwx)
if [ $? == 0 ]
then
     check=$((check+1))

fi
if [ $check -eq 5 ]
then
        echo -e "\e[1;32m-----Task Successful-----\e[0m"
else
        echo -e "\e[1;31m-----Task not Successful-----\e[0m"
fi
	;;

	task13)
echo -e "\e[1;34m===========================================================\e[0m"
echo -e "\e[1;34m Grading RHCSA-Section1 Task13 \e[0m"
echo -e "\e[1;34m===========================================================\e[0m"

check=0
while IFS=":" read -r v1 v2 v3 v4 v5 v6 v7
do
        if [[ $v1 == 'rina' ]]
        then
                check=$((check+1))
        fi
done < /etc/passwd

ls / > zip.txt
var1=$(cat zip.txt | grep fdata)
if [ $? == 0 ]
then
      check=$((check+1))
fi

ls -ll > fip.txt
var2=$(cat fip.txt | grep rina)
if [ $? == 0 ]
then
        check=$((check+1))
fi

ls -ll | grep fdata > kip2.txt
var2=$(cat kip2.txt | grep dr-x)
if [ $? == 0 ]
then
     check=$((check+1))
fi
if [ $check -eq 4 ]
then
        echo -e "\e[1;32m-----Task Successful-----\e[0m"
else
        echo -e "\e[1;31m-----Task not Successful-----\e[0m"
fi
	;;

	task14)
echo -e "\e[1;34m===========================================================\e[0m"
echo -e "\e[1;34m Grading RHCSA-Section1 Task14 \e[0m"
echo -e "\e[1;34m===========================================================\e[0m"
check=0
while IFS=":" read -r v1 v2 v3 v4 v5 v6 v7
do
        if [[ $v1 == 'rohit' ]]
        then
                check=$((check+1))
        fi
done < /etc/passwd

ls / > tip.txt
var1=$(cat tip.txt | grep realme)
if [ $? == 0 ]
then
      check=$((check+1))
fi

ls -ll > fip1.txt
var2=$(cat fip1.txt | grep rohit)
if [ $? == 0 ]
then
        check=$((check+1))
fi

ls -ll | grep realme > kip3.txt
var2=$(cat kip3.txt | grep drwx)
if [ $? == 0 ]
then
     check=$((check+1))
fi
if [ $check -eq 4 ]
then
        echo -e "\e[1;32m-----Task Successful-----\e[0m"
else
        echo -e "\e[1;31m-----Task not Successful-----\e[0m"
fi
	;;

	
	task15)
echo -e "\e[1;34m===========================================================\e[0m"
echo -e "\e[1;34m Grading RHCSA-Section1 Task15 \e[0m"
echo -e "\e[1;34m===========================================================\e[0m"
check=0
while IFS=":" read -r v1 v2 v3 v4 v5 v6 v7
do
        if [[ $v1 == 'alpha' ]]
        then
                check=$((check+1))
        fi
done < /etc/passwd

while IFS=":" read -r v1 v2 v3 v4 v5 v6 v7
do
        if [[ $v1 == 'beta' ]]
        then
                check=$((check+1))
        fi
done < /etc/passwd

while IFS=":" read -r v1 v2 v3 v4 v5 v6 v7
do
        if [[ $v1 == 'gama' ]]
        then
                check=$((check+1))
        fi
done < /etc/passwd

while IFS=":" read -r v1 v2 v3 v4 v5 v6 v7
do
        if [[ $v1 == 'theta' ]]
        then
                check=$((check+1))
        fi
done < /etc/passwd

while IFS=":" read -r v1 v2 v3 v4 v5 v6 v7
do
        if [[ $v1 == 'delta' ]]
        then
                check=$((check+1))
        fi
done < /etc/passwd

while IFS=":" read -r v1 v2 v3 v4 v5 v6 v7
do
        if [[ $v1 == 'table' ]]
        then
                check=$((check+1))
        fi
done < /etc/group

while IFS=":" read -r v1 v2 v3 v4 v5 v6 v7
do
        if [[ $v4 == 'alpha' ]]
        then
                check=$((check+1))
        fi
done < /etc/group

while IFS=":" read -r v1 v2 v3 v4 v5 v6 v7
do
        if [[ $v4 == 'beta' ]]
        then
                check=$((check+1))
        fi
done < /etc/group

ls -l /mnt | grep mydata > xip2.txt
var4=$(cat xip2.txt | grep dr-xr--r--)
if [ $? == 0 ]
then
     check=$((check+1))
fi
if [ $check -eq 9 ]
then
        echo -e "\e[1;32m-----Task Successful-----\e[0m"
else
        echo -e "\e[1;31m-----Task not Successful-----\e[0m"
fi
	;;
	esac
fi

